#pragma once

#include <windows.h>

enum {
	FEATURE_ID_RESERVED = 0,
	FEATURE_ID_ARBITRATION,
	FEATURE_ID_POWER_MANAGEMENT,
	FEATURE_ID_LBA_RANGE_TYPE,
	FEATURE_ID_TEMPERATURE_THRESHOLD,
	FEATURE_ID_ERROR_RECOVERY,
	FEATURE_ID_VOLATILE_WRITE_CACHE,
	FEATURE_ID_NUMBER_OF_QUEUES,
	FEATURE_ID_INTERRUPT_COALESCING,
	FEATURE_ID_INTERRUPT_VECTOR_CONFIGURATION,
	FEATURE_ID_WRITE_ATOMICITY_NORMAL,
	FEATURE_ID_ASYNCHRONOUS_EVENT_CONFIGURATION,
	FEATURE_ID_AUTONOMOUS_POWER_STATE_TRANSITION,
	FEATURE_ID_HOST_MEMORY_BUFFER,
	FEATURE_ID_TIMESTAMP,
	FEATURE_ID_KEEP_ALIVE_TIMER,
	FEATURE_ID_HOST_CONTROLLED_THREMAL_MANAGEMENT,
	FEATURE_ID_NON_OPERATIONAL_POWER_STATE_CONFIG, // 11h
	FEATURE_ID_SOFTWARE_PROGRESS_MARKER = 0x80,
	FEATURE_ID_HOST_IDENTIFIER,
	FEATURE_ID_RESERVATION_NOTIFICATION_MASK,
	FEATURE_ID_RESERVATION_PERSISTENCE, // 83h
};

int iNVMeGetFeatures(HANDLE _hDevice);
