#pragma once

#include <windows.h>

enum {
    IDENTIFY_CNS_NAMESPACE = 0,
    IDENTIFY_CNS_CONTROLLER,
    IDENTIFY_CNS_ACTIVE_NSID_LIST,
    IDENTIFY_CNS_IDENTIFICATION_DESCRIPTION, // 03h
    // 04h to 0Fh are reserved
    IDENTIFY_CNS_ALLOCATED_NSID_LIST = 0x10, // 10h,
    IDENTIFY_CNS_NAMESPACE_ALLOCATED,
    IDENTIFY_CNS_CONTROLLER_LIST_ATTACHED_TO_NAMESPACE,
    IDENTIFY_CNS_CONTROLLER_LIST_IN_SUBSYSTEM,
    IDENTIFY_CNS_PRIMARY_CONTROLLER_CAPABILITIES,
    IDENTIFY_CNS_SECONDARY_CONTROLLER_LIST, // 15h
    // 16h to 1Fh, 20h to FFh are reserved
};

int iNVMeIdentify(HANDLE _hDevice);
