#pragma once

#include <windows.h>

enum {
	LOG_ID_RESERVED = 0,
	LOG_ID_ERROR_INFORMATION,
	LOG_ID_SMART,
	LOG_ID_FIRMWARE_SLOT_INFORMATION,
	LOG_ID_CHANGED_NAMESPACE_LIST,
	LOG_ID_COMMAND_SUPPORTED_AND_EFFECTS,
	LOG_ID_DEVICE_SELF_TEST,
	LOG_ID_TELEMETRY_HOST_INITIATED,
	LOG_ID_TELEMETRY_CONTROLLER_INITIATED, // 0x08h
	LOG_ID_DISCOVERY = 0x70,
	LOG_ID_RESERVATION_NOTIFICATION = 0x80,
	LOG_ID_SANITIZE_STATUS,
};

int iNVMeGetLogPage(HANDLE _hDevice);

