name: cpplint

on:
  push:
  
  pull_request:
    branches: [ "main" ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v4
      - name: Setup cpplint
        run: pip install cpplint
      - name: Linting
        run: cpplint --recursive .
